version: '3.8'

services:

  api-dotnet:
    image: mcr.microsoft.com/dotnet/aspnet:latest
    container_name: agroesfera-api-dotnet
    ports:
      - "5000:5000"

  api-java:
    image: eclipse-temurin:latest
    container_name: agroesfera-api-java
    ports:
      - "8080:8080"
